server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  profiles:
    include: local, jwt, oauth, aws

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 10MB # 업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
      max-request-size: 10MB #multipart/form-data 요청의 최대 허용 크기. 기본 10MB


jwt:
  expiration:
    access: ${ACCESS_EXPIRATION:1800000}
    refresh: ${REFRESH_EXPIRATION:2592000000}
  secret: ${JWT_SECRET:O0qN1qz7fFvYWq6m1HZjlpajM3U4Yjrcm1DQxq8PjVrNZo+M8c2AtbT/1E84exuGdR8zNQG4Yp2xj0FSLxK+Dw==}

kakao:
  oauth:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    frontend-redirect-uri: ${KAKAO_FRONTEND_REDIRECT_URI}

gemini:
  api:
    key: ${GEMINI_API_KEY}

cloud:
  aws:
    s3:
      bucket: promptmate
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false